import Head from 'next/head'
import Layout from '../components/custom/Layout'
import styles from '../styles/Home.module.scss'
import 'semantic-ui-css/semantic.min.css'
import FormExampleFieldControl from '../components/custom/Form'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tak Fabrications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1 className={styles.title}>
          Welcome to Next.js!
        </h1>
        <FormExampleFieldControl />
      </Layout>
    </div>
  )
}
