import Head from "next/head";
import Layout from "../components/custom/Layout";
import "semantic-ui-css/semantic.min.css";
import FormExampleFieldControl from "../components/custom/Form";
import About from "../components/custom/About";
import Home from "../components/custom/Home";
import ServiceContent from "../components/custom/ServiceContent";
import Gallery from "../components/custom/Gallery";
import Approach from "../components/custom/Approach";
import { ParallaxProvider } from "react-scroll-parallax";
import ParallaxImage from "../components/common/ParallaxImage";
import UnderConstruction from "./UnderConstruction";
export default function MainHome() {
  return (
    <div>
      <Head>
        <title>Tak Fabrications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ParallaxProvider>
        {/* commented below section for under construction changes */}
          <Home />
          <About />
          <Approach />
          <ParallaxImage />
          <Gallery />
          <FormExampleFieldControl />
        {/* <UnderConstruction/> */}
      </ParallaxProvider>


      
    </div>
  );
}
